version: '3'
services:
  validator-alice:
    image: parity/polkadot:v0.9.24
    ports:
      - '40333:30333'
      - '6644:9944'
      - '6633:9933'
    volumes:
      - ./:/data
    command:
      - --chain=/data/chainspecs/rococo-local-raw.json
      - --base-path=/data/.tmp_alice_data
      - --port=30333
      - --ws-port=9944
      - --rpc-port=9933
      - --rpc-cors=all
      - --unsafe-rpc-external
      - --unsafe-ws-external
      - --validator
      - --alice
      - --no-prometheus
      - --no-telemetry
    networks:
      paradao_net:
        ipv4_address: 172.28.1.1
        aliases:
          - alice

  validator-bob:
    image: parity/polkadot:v0.9.24
    ports:
      - '30334:30333'
      - '6677:9944'
      - '6655:9933'
    volumes:
      - ./:/data
    command:
      - --chain=/data/chainspecs/rococo-local-raw.json
      - --base-path=/data/.tmp_bob_data
      - --port=30333
      - --ws-port=9944
      - --rpc-port=9933
      - --rpc-cors=all
      - --unsafe-rpc-external
      - --unsafe-ws-external
      - --validator
      - --bob
      - --no-prometheus
      - --no-telemetry
    networks:
      paradao_net:
        ipv4_address: 172.28.1.2
        aliases:
          - bob

  paradao-genesis-state:
    image: paradao/paradao-collator:v0.1.0
    volumes:
      - paradao-genesis-state:/data
    command: >
      /usr/bin/parachain-collator
      export-genesis-state
      --chain /chainspecs/rococo-local-parachain-2000-raw.json /data/para-2000-genesis

  paradao-wasm-runtime:
    image: paradao/paradao-collator:v0.1.0
    volumes:
      - paradao-wasm-runtime:/data
    command: >
      /usr/bin/parachain-collator
      export-genesis-wasm
      --chain /chainspecs/rococo-local-parachain-2000-raw.json /data/para-2000-wasm

  registrar:
    image: paradao/registrar:v0.1.0
    volumes:
      - paradao-genesis-state:/paradao-genesis-state
      - paradao-wasm-runtime:/paradao-wasm-runtime
    depends_on:
      - validator-alice
      - validator-bob
      - paradao-wasm-runtime
      - paradao-genesis-state
    networks:
      paradao_net:

  paradao-collator:
    image: paradao/paradao-collator:v0.1.0
    ports:
      - '30333:30333'
      - '9944:9944'
      - '9933:9933'
    volumes:
      - ./:/data
    depends_on:
      - validator-alice
      - validator-bob
    command: >
      /usr/bin/docker-run-paradao-collator.sh
    networks:
      paradao_net:
        ipv4_address: 172.28.1.8
        aliases:
          - paradao-collator

  zeitgeist-dev:
    image: zeitgeistpm/zeitgeist-node:723171517d5c7ea94b9bb22ea9289c2dd8d7fc5f
    ports:
      - '20333:30333'
      - '8844:9944'
      - '8833:9933'
    volumes:
      - ./:/data
    command:
      - --dev
      - --base-path=/data/.tmp_zg_data
      - --port=30333
      - --ws-port=9944
      - --rpc-port=9933
      - --rpc-cors=all
      - --unsafe-rpc-external
      - --unsafe-ws-external
      - --no-prometheus
      - --no-telemetry

volumes:
  paradao-genesis-state:
  paradao-wasm-runtime:

networks:
  paradao_net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16


